name: Zenmail Ninja Scraper
on:
  repository_dispatch:
    types: [manual_trigger]
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        # Isse puppeteer jaldi install hoga bina faltu chrome download kiye
        run: |
          npm install
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Scraper
        run: node scraper.js
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
          PUPPETEER_EXECUTABLE_PATH: '/usr/bin/google-chrome'
